/*
 * user-service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UserList struct {

	Count int32 `json:"count,omitempty"`

	Users []User `json:"users,omitempty"`
}
