# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    env:
      PROJECT_NAME: userservice

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: echo
        run: echo $PROJECT_NAME

      - name: Get the version
        id: tag
        run: echo ::set-output name=tag::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: build docker image
        run: docker build -t "${{secrets.HUB_DOCKER_NAME}}/$PROJECT_NAME:${{steps.tag.outputs.tag}}"" ./server/

      - name: login to docker
        run : docker login --username ${{secrets.HUB_DOCKER_NAME}} --password $HUB_DOCKER_PASSWORD

      - name: push image
        run: docker push "${{secrets.HUB_DOCKER_NAME}}/$PROJECT_NAME:${{steps.tag.outputs.tag}}""