# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  PROJECT_NAME: userservice

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: build docker image
        run: docker build -t $HUB_DOCKER_NAME/$PROJECT_NAME$$:{{steps.tag.outputs.tag}} ./server/

      - name: login to docker
        run : docker login --username $HUB_DOCKER_NAME --password $HUB_DOCKER_PASSWORD

      - name: push image
        run: docker push $HUB_DOCKER_NAME/$PROJECT_NAME$$:{{steps.tag.outputs.tag}}